server:
  port: 8002
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/dbspringcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sumeng.springcloud.entity
eureka:
  client:
    #    true 表示将自己注册进eureka server端
    register-with-eureka: true
    #    是否从eureka server端抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
#    eureak 客户端向服务端发送心跳时间间隔，单位为秒（默认30s）
    lease-renewal-interval-in-seconds: 5
#    eureak 服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90s），超市将提出服务
    lease-expiration-duration-in-seconds: 10

